sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.27.4

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - REACT_APP_API_URL=http://127.0.0.1
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
  - sudo sysctl -p
  - docker-compose up --build -d

script:
  # - docker-compose exec users python manage.py test
  - docker-compose exec users python manage.py flake8
  - docker-compose exec client npm test -- --coverage

after_script:
  - docker-compose down

after_success:
  - docker build -t chimailo/witti-server ./services/app
  - docker build -t chimailo/witti-client ./services/client
  - docker build -t chimailo/witti-nginx ./services/nginx

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to docker hub
  - docker push chimailo/witti-server
  - docker push chimailo/witti-client
  - docker push chimailo/witti-nginx
