version: '3.3'

services:
  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data/
        volume:
          nocopy: true

  app:
    build:
      context: ./services/app
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - APP_SETTINGS=src.config.ProductionConfig
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_APP=src/__init__.py
      - FLASK_ENV=production
      - SECRET_KEY={SECRET_KEY}

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: client
    stdin_open: true

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
      - client
    restart: always

volumes:
  postgres_data:
