version: '3.3'

services:
  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    build:
      context: ./services/app
      dockerfile: Dockerfile.dev
    command: python manage.py run -h 0.0.0.0
    volumes:
      - type: bind
        source: ./services/app
        target: /usr/src/app
    environment:
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE=postgres
      - FLASK_APP=src/__init__.py
      - FLASK_ENV=development
      - SQL_HOST=db
      - SQL_PORT=5432
    expose:
      - 5000
    depends_on:
      - db

  # client:
  #   build:
  #     context: ./services/client
  #     dockerfile: Dockerfile.dev
  #   depends_on:
  #     - app
  #   environment:
  #     - NODE_ENV=development
  #     - REACT_APP_API_URL=http://localhost/api
  #   ports:
  #     - 3000:3000
  #   stdin_open: true
  #   volumes:
  #     - './services/client:/usr/src/app'
  #     - '/usr/src/app/node_modules'

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - app
      # - client
    ports:
      - 80:80
    restart: always
