SELECT messages.id AS messages_id, messages.author_id AS messages_author_id, messages.created_on AS messages_created_on, messages.body AS messages_body, messages.is_read AS messages_is_read, messages.conversation_id AS messages_conversation_id, users_1.created_on AS users_1_created_on, users_1.updated_on AS users_1_updated_on, users_1.id AS users_1_id, users_1.username AS users_1_username, users_1.email AS users_1_email, users_1.password AS users_1_password, users_1.is_active AS users_1_is_active, users_1.is_admin AS users_1_is_admin, users_1.sign_in_count AS users_1_sign_in_count, users_1.current_sign_in_on AS users_1_current_sign_in_on, users_1.current_sign_in_ip AS users_1_current_sign_in_ip, users_1.last_sign_in_on AS users_1_last_sign_in_on, users_1.last_sign_in_ip AS users_1_last_sign_in_ip, users_1.last_message_read_time AS users_1_last_message_read_time, users_2.created_on AS users_2_created_on, users_2.updated_on AS users_2_updated_on, users_2.id AS users_2_id, users_2.username AS users_2_username, users_2.email AS users_2_email, users_2.password AS users_2_password, users_2.is_active AS users_2_is_active, users_2.is_admin AS users_2_is_admin, users_2.sign_in_count AS users_2_sign_in_count, users_2.current_sign_in_on AS users_2_current_sign_in_on, users_2.current_sign_in_ip AS users_2_current_sign_in_ip, users_2.last_sign_in_on AS users_2_last_sign_in_on, users_2.last_sign_in_ip AS users_2_last_sign_in_ip, users_2.last_message_read_time AS users_2_last_message_read_time, profiles_1.created_on AS profiles_1_created_on, profiles_1.updated_on AS profiles_1_updated_on, profiles_1.id AS profiles_1_id, profiles_1.name AS profiles_1_name, profiles_1.avatar AS profiles_1_avatar, profiles_1.dob AS profiles_1_dob, profiles_1.bio AS profiles_1_bio, profiles_1.user_id AS profiles_1_user_id, profiles_2.created_on AS profiles_2_created_on, profiles_2.updated_on AS profiles_2_updated_on, profiles_2.id AS profiles_2_id, profiles_2.name AS profiles_2_name, profiles_2.avatar AS profiles_2_avatar, profiles_2.dob AS profiles_2_dob, profiles_2.bio AS profiles_2_bio, profiles_2.user_id AS profiles_2_user_id 
FROM messages
JOIN (
    SELECT messages.conversation_id AS conversation_id, max(messages.created_on) AS last_message 
    FROM messages
	GROUP BY messages.conversation_id
) AS anon_1 ON messages.created_on = anon_1.last_message
JOIN conversation ON conversation.id = messages.conversation_id
JOIN users AS users_1 ON users_1.id = conversation.user1_id
JOIN users AS users_2 ON users_2.id = conversation.user2_id
LEFT OUTER JOIN profiles AS profiles_1 ON users_1.id = profiles_1.user_id
LEFT OUTER JOIN profiles AS profiles_2 ON users_2.id = profiles_2.user_id
WHERE conversation.user1_id = 5 OR conversation.user2_id = 5
ORDER BY anon_1.last_message DESC