# base image
FROM node:14.2.0-alpine3.11

# set working directory
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
COPY package-lock.json /usr/src/app/package-lock.json

RUN npm install
RUN npm install react-scripts@3.4.1 -g --silent

COPY . /usr/src/app

# start app
CMD ["npm", "start"]
